"""Manual integration test for Step 8 — ScriptExecutor.

Finds the most recent main.py generated by test_claude_api.py in the workspaces
directory and runs it with ScriptExecutor, verifying stdout capture.

If no script exists yet, it creates a small inline test script that mimics the
Step 7 output (loop + sleep + print) so you can test the executor independently.

Run:
    python scripts/test_executor.py
"""

from __future__ import annotations

import asyncio
import logging
import os
import sys
import textwrap
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")

FALLBACK_SCRIPT = textwrap.dedent("""\
    import time

    for i in range(3):
        print(f"Hello Claude Experiment  (iteration {i+1}/3)")
        time.sleep(1)

    print("Done.")
""")


def _find_latest_script() -> Path | None:
    """Return the most recently modified main.py under workspaces/."""
    base = Path(__file__).parent.parent / "workspaces"
    candidates = sorted(base.rglob("main.py"), key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0] if candidates else None


async def main() -> None:
    from claude_feishu_flow.runner.executor import ScriptExecutor

    # Find or create the test script
    script_path_obj = _find_latest_script()
    if script_path_obj:
        print(f"Found generated script: {script_path_obj}")
    else:
        print("No generated script found in workspaces/. Using inline fallback script.")
        fallback_dir = Path(__file__).parent.parent / "workspaces" / "task_test_executor"
        fallback_dir.mkdir(parents=True, exist_ok=True)
        script_path_obj = fallback_dir / "main.py"
        script_path_obj.write_text(FALLBACK_SCRIPT, encoding="utf-8")
        print(f"Written fallback script to: {script_path_obj}")

    script_path = str(script_path_obj)

    # ------------------------------------------------------------------
    # Test 1: Normal execution
    # ------------------------------------------------------------------
    print("\n=== Test 1: ScriptExecutor.run (normal) ===")
    executor = ScriptExecutor(default_timeout=30.0)
    try:
        result = await executor.run(script_path)
        print(f"[PASS] returncode={result.returncode}  duration={result.duration_seconds:.2f}s")
        print(f"       success={result.success}")
        print(f"\n--- stdout ({len(result.stdout)} bytes) ---")
        print(result.stdout.rstrip())
        print("---")
        if result.stderr:
            print(f"\n--- stderr ---\n{result.stderr.rstrip()}\n---")

        checks = [
            ("returncode == 0",          result.returncode == 0),
            ("stdout is non-empty",      len(result.stdout.strip()) > 0),
            ("'Hello' in stdout",        "Hello" in result.stdout),
            ("duration > 2s (3×sleep1)", result.duration_seconds > 2.0),
        ]
        print("\n=== Sanity checks ===")
        for label, ok in checks:
            print(f"{'[PASS]' if ok else '[FAIL]'} {label}")

    except Exception as e:
        print(f"[FAIL] executor.run: {e}")
        return

    # ------------------------------------------------------------------
    # Test 2: Timeout enforcement
    # ------------------------------------------------------------------
    print("\n=== Test 2: ScriptExecutor.run (timeout=0.5s) ===")
    try:
        await executor.run(script_path, timeout=0.5)
        print("[FAIL] Expected TimeoutError but script completed")
    except asyncio.TimeoutError:
        print("[PASS] TimeoutError raised correctly")
    except Exception as e:
        print(f"[FAIL] Unexpected exception: {e}")

    print("\nDone.")


if __name__ == "__main__":
    asyncio.run(main())
